export const translations = {
    pt: {
        title: "ANIME ROULETTE",
        subtitle: "Descubra seu próximo anime",
        userLabel: "Usuário",
        sourceLabel: "Origem",
        genreLabel: "Gênero",
        scoreMin: "Nota Mín.",
        scoreMax: "Nota Máx.",
        spinBtn: "Girar",
        any: "Todos",
        sourceGlobal: "Todos",
        sourcePlanning: "PLANNING",
        detailsBtn: "Detalhes no AniList",
        historyTitle: "Sorteios Recentes",
        noHistory: "Nenhum anime sorteado ainda.",
        clearHistory: "Limpar",
        errorFilterTitle: "Erro de Filtro",
        errorFilterMsg: "A nota mínima não pode ser maior que a máxima.",
        errorNotFoundTitle: "Nenhum anime encontrado",
        errorNotFoundMsg: "Não encontramos nada com esses filtros!",
        errorUserTitle: "Usuário Inválido",
        errorUserMsg: "Não encontramos o perfil informado ou a conta é privada.",
        errorEmptyListTitle: "Lista Vazia",
        errorEmptyListMsg: "Sua lista de 'Planning' está vazia no AniList.",
        userHelp: "Você pode digitar um único nick ou vários separados por vírgula (ex: Nick1, Nick2). O sorteio buscará animes de todos esses perfis.",
        nsfwFilter: "Esconder conteúdo adulto",
        genres: {
            all: "Todos",
            action: "Ação",
            adventure: "Aventura",
            comedy: "Comédia",
            drama: "Drama",
            romance: "Romance",
            fantasy: "Fantasia",
            scifi: "Ficção Científica",
            horror: "Terror",
            mystery: "Mistério",
            slice: "Slice of Life",
            thriller: "Suspense",
            supernatural: "Sobrenatural"
        }
    },
    en: {
        title: "ANIME ROULETTE",
        subtitle: "Find your next anime",
        userLabel: "User",
        sourceLabel: "Source",
        genreLabel: "Genre",
        scoreMin: "Min Score",
        scoreMax: "Max Score",
        spinBtn: "Spin",
        any: "All",
        sourceGlobal: "All",
        sourcePlanning: "PLANNING",
        detailsBtn: "AniList Details",
        historyTitle: "Recent Spins",
        noHistory: "No animes spun yet.",
        clearHistory: "Clear All",
        errorFilterTitle: "Filter Error",
        errorFilterMsg: "Min score cannot be higher than max score.",
        errorNotFoundTitle: "No anime found",
        errorNotFoundMsg: "We couldn't find anything with these filters!",
        errorUserTitle: "Invalid User",
        errorUserMsg: "Profile not found or it is set to private.",
        errorEmptyListTitle: "Empty List",
        errorEmptyListMsg: "Your 'Planning' list is empty on AniList.",
        userHelp: "You can enter a single nick or multiple separated by commas (e.g., Nick1, Nick2). The draw will fetch anime from all these profiles.",
        nsfwFilter: "Hide adult content",
        genres: {
            all: "All",
            action: "Action",
            adventure: "Adventure",
            comedy: "Comedy",
            drama: "Drama",
            romance: "Romance",
            fantasy: "Fantasy",
            scifi: "Sci-Fi",
            horror: "Horror",
            mystery: "Mystery",
            slice: "Slice of Life",
            thriller: "Thriller",
            supernatural: "Supernatural"
        }
    }
};