export const translations = {
    pt: {
        title: "ANIME ROULETTE",
        subtitle: "Descubra seu próximo anime",
        userLabel: "Usuário",
        sourceLabel: "Origem",
        genreLabel: "Gênero",
        scoreMin: "Nota Mín.",
        scoreMax: "Nota Máx.",
        spinBtn: "Girar",
        any: "Todos",
        sourceGlobal: "Todos",
        sourcePlanning: "Minha Lista (Planning)",
        detailsBtn: "Detalhes no AniList",
        historyTitle: "Sorteios Recentes",
        noHistory: "Nenhum anime sorteado ainda.",
        historyTitle: "Sorteios Recentes",
        clearHistory: "Limpar",
        errorFilterTitle: "Erro de Filtro",
        errorFilterMsg: "A nota mínima não pode ser maior que a máxima.",
        errorNotFoundTitle: "Nenhum anime encontrado",
        errorNotFoundMsg: "Não encontramos nada com esses filtros. Tente mudar o gênero ou buscar no catálogo geral!",
        errorUserTitle: "Usuário Inválido",
        errorUserMsg: "Não encontramos o perfil informado. Verifique o nick ou a privacidade da conta."  
    },
    en: {
        title: "ANIME ROULETTE",
        subtitle: "Find your next anime",
        userLabel: "User",
        sourceLabel: "Source",
        genreLabel: "Genre",
        scoreMin: "Min Score",
        scoreMax: "Max Score",
        spinBtn: "Spin",
        any: "All",
        sourceGlobal: "All",
        sourcePlanning: "Planning List",
        detailsBtn: "AniList Details",
        historyTitle: "Recent Spins",
        noHistory: "No animes spun yet.",
        historyTitle: "Recent Spins",
        clearHistory: "Clear All",
        errorFilterTitle: "Filter Error",
        errorFilterMsg: "Min score cannot be higher than max score.",
        errorNotFoundTitle: "No anime found",
        errorNotFoundMsg: "We couldn't find anything with these filters. Try changing the genre or searching the general catalog!",
        errorUserTitle: "Invalid User",
        errorUserMsg: "We couldn't find the specified profile. Check the username or account privacy."
    }
};